---
title: "hw6"
author: "Senna"
date: "2024-11-30"
output: github_document
---

```{r}
library(tidyverse)
library(broom)
library(ggplot2)
library(purrr)
library(modelr)
library(rsample)
```



## Problem 1
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
n_boot = 5000

boot_results = replicate (n_boot, {
  sample = weather_df %>% sample_frac(replace = TRUE) #why true?
  
  model = lm(tmax ~tmin, data= sample)
  
  r_sqr = glance(model)$r.squared
  
  coefs = tidy(model)
  log_beta = log(coefs$estimate[1] * coefs$estimate[2])
  
  c(r_sqr, log_beta)
  
}, simplify = "matrix")

boot_results = t(boot_results)
colnames(boot_results) = c("r_sqr", "log_beta")

bootstrap_df = as.data.frame(boot_results)
```

```{r}
ci_r_sqr = quantile(bootstrap_df$r_sqr, probs = c(0.025,0.975))
ci_log_beta = quantile(bootstrap_df$log_beta, probs = c(0.025, 0.975))

print("95% CI for R^2:")
print(ci_r_sqr)

print("95% CI for log(β^0 * β^1):")
print(ci_log_beta)

```
```{r}
ggplot(bootstrap_df, aes(x = r_sqr))+
  geom_density (color ='red', alpha = 0.5)+
  labs(title = "bootstap distribution of R^2", x="R^2", y="density")

ggplot(bootstrap_df, aes(x = log_beta))+
  geom_density (color='blue',alpha = 0.5)+
  labs(title = "bootstap distribution of log(β^0 * β^1)", x="R^2", y="density")
```


## Problem 2

```{r}
homicide_df = read.csv("./data/homicide-data.csv")|>
  mutate(
    city_state = paste(city, state, sep=","),
    solved = if_else(disposition == "Closed by arrest",1,0),
    victim_age = as.numeric(victim_age),
    victim_sex = as.factor(victim_sex),
    victim_race = as.factor(victim_race),
    solved = as.factor(solved)
  )

filtered = homicide_df|>
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black"),
    !is.na(victim_age)
  )
```
```{r}
baltimore_df = filtered |>
  filter(city_state == "Baltimore,MD")

baltimore_model = glm(
  solved ~ victim_age + victim_sex + victim_race,
  family = binomial,
  data = baltimore_df
)

baltimore_results = tidy(baltimore_model, conf.int = TRUE, exp = TRUE) # true true?

sex_diff = baltimore_results|>
  filter (term == "victim_sexMale")|>
  select(estimate = estimate, conf.low, conf.high)

print(sex_diff)
```
```{r}
city_model = filtered|>
  group_by(city_state)|>
   filter(
    n_distinct(victim_sex) > 1,  
    n_distinct(victim_race) > 1   
  ) |>
  nest()|>
  mutate(
    model = map(data, ~glm(solved ~ victim_age + victim_sex + victim_race, family = binomial, data = .x)),
    results = map(model, ~tidy(.x, conf.int = TRUE, exp = TRUE))
  )|>
  unnest(results)|>
  filter(term == "victim_sexMale")|>
  select(city_state, estimate = estimate, conf.low, conf.high)
```
```{r}
ordered_results = city_model|> arrange(estimate)

ggplot(ordered_results, aes(x= reorder(city_state, estimate), y = estimate))+
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  labs(
    title = "adjusted odds ratio for solved homicides",
    x = "city",
    y = "adjusted odds ratio: male vs female"
  )+
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)  
  )
```
COMMENT ON THE PLOT

## Problem 3

```{r}
bw_df = read.csv("./data/birthweight.csv")
glimpse(bw_df)
```

```{r}
bw_df <- bw_df |>
  mutate(
    babysex = factor(babysex, labels = c("Male", "Female")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9), 
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
    mrace = factor(mrace, levels = c(1, 2, 3, 4, 8), 
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other")),
    malform = factor(malform, levels = c(0, 1), labels = c("Absent", "Present"))
  )

bw_df |>
  summarize(across(everything(), ~ sum(is.na(.))))
```
no missing values.




The factors influencing birth weight (bwt) can include:

Biological factors: bhead, blength, gaweeks, malform.
Maternal factors: ppbmi, ppwt, wtgain, momage, mheigth, smoken.
Socioeconomic factors: fincome, frace, mrace.

```{r}
# proposing a regression model

bwt_model <- lm(bwt ~ bhead + blength + gaweeks + malform + ppbmi + ppwt + wtgain + momage + mheight + smoken + fincome + frace, 
                data = bw_df)

summary(bwt_model)

```
```{r}
# model residual vs fitted values

bw_df = bw_df |>
  add_predictions(bwt_model)|>
  add_residuals(bwt_model)

ggplot(bw_df, aes(x=pred, y=resid))+
  geom_point()+
  geom_hline(yintercept=0, linetype = 'dashed')+
  labs(
    title = "residuals vs fitted values",
    x = "predicted birth weight (fitted)",
    y = "residuals"
  )
```

```{r}
# length and gestational age
model2 <- lm(bwt ~ blength + gaweeks, data = bw_df)

# head circumference, length, sex, all interactions
model3 <- lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead * blength * babysex, data = bw_df)
```


```{r}
set.seed(123)

cv_splits = tibble(
  splits = replicate(
    100,
    initial_split(bw_df, prop = 0.8), # 80% training, 20% testing
    simplify = FALSE
  )
)

calc_rmse = function (split, model_formula) {
  train = analysis(split)
  test = analysis(split)
  
  model = lm(model_formula, data = train)
  
  pred = predict(model, newdata = test)
  
  rmse = sqrt(mean((test$bwt - pred)^2, na.rm=TRUE))
  
  return(rmse)
}
```

```{r}
cv_res <- cv_splits |>
  mutate(
    rmse_model_proposed = map_dbl(splits, ~ calc_rmse(.x, model_formula = bwt ~ bhead + blength + gaweeks + malform + ppbmi + ppwt + wtgain + momage + mheight + smoken + fincome + frace)),
    rmse_model2 = map_dbl(splits, ~ calc_rmse(.x, model_formula = bwt ~ blength + gaweeks)),
    rmse_model3 = map_dbl(splits, ~ calc_rmse(.x, model_formula = bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex))
  )

cv_res |>
  summarise(
    mean_rmse_proposed = mean(rmse_model_proposed),
    mean_rmse_model2 = mean(rmse_model2),
    mean_rmse_model3 = mean(rmse_model3)
  )
```
```{r}
rmse_long <- cv_res |>
  select(rmse_model_proposed, rmse_model2, rmse_model3) |>
  pivot_longer(cols = everything(), names_to = "model", values_to = "rmse")

# Plot RMSE distributions
ggplot(rmse_long, aes(x = model, y = rmse)) +
  geom_boxplot() +
  labs(title = "RMSE Comparison Across Models", x = "Model", y = "RMSE") +
  theme_minimal()
```









